version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "eslint"
        versions:
          - "10.x"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
